name: CI Docker

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build local Docker image
      run: docker build -t hybrid-compute .

    - name: Test local Docker image
      run: docker run --rm hybrid-compute

    - name: Build CUDA Docker image
      run: docker build -f Dockerfile.cuda -t hybrid-compute-cuda .

    # Note: CUDA testing requires GPU runners, so only build is tested here